"""Add game_user Association Table

Revision ID: 4ce443f483b2
Revises: 6da2e30e5ef9
Create Date: 2025-03-07 19:54:21.252324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce443f483b2'
down_revision = '6da2e30e5ef9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
